### ISSUE TITLE
Multiple attempts to verify the base URL.

### ISSUE THREAD

**Issue by jrbenny35** [pytest-dev/pytest-base-url#3]
I think it would be nice to have multiple attempts at trying to verify the base URL, especially if a server is starting up. Maybe just a number of attempts, or a max time allowed.

**Comment by davehunt** [comment]
I agree this would be a useful enhancement, though I believe it should be a low timeout by default. Maybe when verifying the base URL is enabled, we could retry every second up to 10 seconds by default. The timeout value could then be tweaked via a command line options such as `--verify-base-url-timeout`. We'd have to check that the timeout is greater than the poll value.

**Comment by davehunt** [comment]
@jrbenny35 let me know if you're interested in working on this.

**Comment by jrbenny35** [comment]
I am interested! How are you thinking we could implement this?

**Comment by davehunt** [comment]
@jrbenny35 when we verify the URL we should check the timeout value. If it's zero then we should continue as we do currently. If it's less than the polling delay (I'd suggest 1 second) then we should raise an exception. If it's greater than the polling delay then we should retry until the timeout value has been reached. It would be very similar to the waits used in Selenium, however it's trivial to reimplement that here rather than depending on an unnecessary package.

**Comment by jrbenny35** [comment]
This line ```requests.get(base_url, timeout=10)``` has a timeout. Is that what you are referring to?

**Comment by davehunt** [comment]
That means the request will wait for up to 10 seconds, but it's only a single request. Ideally you'd have this with a lower timeout such as 1 second, and repeat if it fails.

**Comment by davehunt** [comment]
That looks neat @nicoddemus! Thanks!
